# Generated by Django 4.2.7 on 2025-12-19 12:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='ایمیل')),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='لطفا یک شماره تلفن معتبر ایرانی وارد کنید (موبایل: 09123456789 یا ثابت: 02112345678)', regex='^(\\+98|0)?(\\d{10}|\\d{11})$')], verbose_name='شماره موبایل')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='موبایل تایید شده')),
                ('email_verified', models.BooleanField(default=False, verbose_name='ایمیل تایید شده')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='تصویر پروفایل')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='بیوگرافی')),
                ('user_type', models.CharField(choices=[('individual', 'حقیقی'), ('business', 'حقوقی')], default='individual', max_length=20, verbose_name='نوع کاربر')),
                ('national_id', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='لطفا یک کد ملی 10 رقمی معتبر وارد کنید.', regex='^\\d{10}$')], verbose_name='کد ملی')),
                ('national_id_verified', models.BooleanField(default=False, verbose_name='کد ملی تایید شده')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='نام شرکت')),
                ('economic_code', models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator(message='لطفا یک کد اقتصادی 14 رقمی معتبر وارد کنید.', regex='^\\d{14}$')], verbose_name='کد اقتصادی')),
                ('organization_role', models.CharField(blank=True, choices=[('owner', 'مالک'), ('admin', 'مدیر'), ('member', 'عضو')], max_length=20, verbose_name='نقش در سازمان')),
                ('language', models.CharField(choices=[('fa', 'فارسی'), ('en', 'انگلیسی')], default='fa', max_length=5, verbose_name='زبان')),
                ('timezone', models.CharField(default='Asia/Tehran', max_length=50, verbose_name='منطقه زمانی')),
                ('currency', models.CharField(default='IRR', max_length=3, verbose_name='واحد پول')),
                ('chat_context', models.JSONField(blank=True, default=dict, help_text='تنظیمات و زمینه کاربر برای تعاملات چت', verbose_name='زمینه گفتگو')),
                ('preferences', models.JSONField(blank=True, default=dict, help_text='تنظیمات UI، تم، و سفارشی\u200cسازی پاسخ', verbose_name='تنظیمات کاربر')),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='احراز هویت دو مرحله\u200cای فعال')),
                ('totp_secret', models.CharField(blank=True, max_length=32, verbose_name='کلید TOTP')),
                ('backup_codes', models.JSONField(blank=True, default=list, verbose_name='کدهای پشتیبان')),
                ('max_concurrent_sessions', models.IntegerField(default=3, verbose_name='حداکثر نشست\u200cهای همزمان')),
                ('last_password_change', models.DateTimeField(blank=True, null=True, verbose_name='آخرین تغییر رمز عبور')),
                ('failed_login_attempts', models.IntegerField(default=0, verbose_name='تلاش\u200cهای ناموفق ورود')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='قفل تا')),
                ('api_key', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='کلید API')),
                ('api_key_created_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ایجاد کلید API')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='آخرین بازدید')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='اعلان\u200cهای ایمیل')),
                ('sms_notifications', models.BooleanField(default=True, verbose_name='اعلان\u200cهای پیامکی')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='اعلان\u200cهای پوش')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='نام سازمان')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/logos/')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='نام حقوقی شرکت')),
                ('economic_code', models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator(message='لطفا یک کد اقتصادی 14 رقمی معتبر وارد کنید.', regex='^\\d{14}$')], verbose_name='Economic Code')),
                ('national_id', models.CharField(blank=True, max_length=11, verbose_name='Company National ID')),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='لطفا یک شماره تلفن معتبر ایرانی وارد کنید (موبایل: 09123456789 یا ثابت: 02112345678)', regex='^(\\+98|0)?(\\d{10}|\\d{11})$')])),
                ('allowed_email_domains', models.TextField(blank=True, help_text='Comma-separated list of allowed email domains for auto-join')),
                ('max_members', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_organizations', to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
            ],
            options={
                'verbose_name': 'سازمان',
                'verbose_name_plural': 'سازمان\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(max_length=255, unique=True)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('device_name', models.CharField(blank=True, max_length=255)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('refresh_token', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نشست کاربر',
                'verbose_name_plural': 'نشست\u200cهای کاربران',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='StaffGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام گروه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('priority', models.IntegerField(default=0, verbose_name='اولویت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('permissions', models.ManyToManyField(blank=True, help_text='دسترسی\u200cهای این گروه کارمندی', to='auth.permission', verbose_name='دسترسی\u200cها')),
            ],
            options={
                'verbose_name': 'گروه کارمندی',
                'verbose_name_plural': 'گروه\u200cهای کارمندی',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'دعوت\u200cنامه سازمان',
                'verbose_name_plural': 'دعوت\u200cنامه\u200cهای سازمان',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('2fa_enabled', '2FA Enabled'), ('2fa_disabled', '2FA Disabled'), ('api_key_generated', 'API Key Generated'), ('profile_updated', 'Profile Updated'), ('organization_created', 'Organization Created'), ('organization_joined', 'Organization Joined'), ('organization_left', 'Organization Left'), ('payment_made', 'Payment Made'), ('subscription_changed', 'Subscription Changed'), ('admin_action', 'Admin Action')], max_length=50)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'لاگ عملیات',
                'verbose_name_plural': 'لاگ\u200cهای عملیات',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.organization', verbose_name='سازمان'),
        ),
    ]
