# Generated by Django 4.2.7 on 2025-12-19 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_currency',
            field=models.ForeignKey(blank=True, help_text='ارز مورد نظر برای نمایش قیمت\u200cها (پیش\u200cفرض: تومان)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by_users', to='finance.currency', verbose_name='ارز ترجیحی'),
        ),
        migrations.AddField(
            model_name='user',
            name='staff_groups',
            field=models.ManyToManyField(blank=True, help_text='فقط برای کارمندان (is_staff=True) استفاده می\u200cشود', related_name='members', to='accounts.staffgroup', verbose_name='گروه\u200cهای کارمندی'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationinvitation',
            unique_together={('organization', 'email')},
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-timestamp'], name='accounts_au_user_id_1110c4_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-timestamp'], name='accounts_au_action_918219_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('user_type', 'individual')), fields=('phone_number',), name='unique_phone_for_individual_users'),
        ),
    ]
