# Generated by Django 4.2.7 on 2025-12-21 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_move_default_gateway'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='currency',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='تصویر پروفایل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_currency',
            field=models.ForeignKey(blank=True, help_text='ارز مورد نظر برای نمایش قیمت\u200cها (پیش\u200cفرض: تومان)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by_users', to='finance.currency', verbose_name='واحد پول'),
        ),
    ]
