# Generated by Django 4.2.7 on 2025-12-21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_language_timezone_models'),
        ('accounts', '0003_update_user_avatar_and_currency'),
    ]

    operations = [
        # اضافه کردن فیلدهای جدید موقت
        migrations.AddField(
            model_name='user',
            name='language_fk',
            field=models.ForeignKey(
                blank=True, 
                null=True, 
                on_delete=django.db.models.deletion.SET_NULL, 
                related_name='users_temp', 
                to='core.language'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone_fk',
            field=models.ForeignKey(
                blank=True, 
                null=True, 
                on_delete=django.db.models.deletion.SET_NULL, 
                related_name='users_temp_tz', 
                to='core.timezone'
            ),
        ),
    ]
