# Generated by Django 4.2.7 on 2025-11-16 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_managers_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'لاگ عملیات', 'verbose_name_plural': 'لاگ\u200cهای عملیات'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['-created_at'], 'verbose_name': 'سازمان', 'verbose_name_plural': 'سازمان\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='organizationinvitation',
            options={'ordering': ['-created_at'], 'verbose_name': 'دعوت\u200cنامه سازمان', 'verbose_name_plural': 'دعوت\u200cنامه\u200cهای سازمان'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterModelOptions(
            name='usersession',
            options={'ordering': ['-last_activity'], 'verbose_name': 'نشست کاربر', 'verbose_name_plural': 'نشست\u200cهای کاربران'},
        ),
    ]
