# Generated by Django 4.2.7 on 2025-12-21

from django.db import migrations
import uuid


def create_and_populate_languages_timezones(apps, schema_editor):
    """ایجاد زبان‌ها و مناطق زمانی پیش‌فرض و تبدیل داده‌های موجود"""
    Language = apps.get_model('core', 'Language')
    Timezone = apps.get_model('core', 'Timezone')
    User = apps.get_model('accounts', 'User')
    
    # ایجاد زبان فارسی (پیش‌فرض)
    fa_lang, _ = Language.objects.get_or_create(
        code='fa',
        defaults={
            'id': uuid.uuid4(),
            'name': 'Persian',
            'native_name': 'فارسی',
            'is_rtl': True,
            'is_active': True,
            'is_default': True,
            'order': 1
        }
    )
    
    # ایجاد زبان انگلیسی
    en_lang, _ = Language.objects.get_or_create(
        code='en',
        defaults={
            'id': uuid.uuid4(),
            'name': 'English',
            'native_name': 'English',
            'is_rtl': False,
            'is_active': True,
            'is_default': False,
            'order': 2
        }
    )
    
    # ایجاد منطقه زمانی تهران (پیش‌فرض)
    tehran_tz, _ = Timezone.objects.get_or_create(
        code='Asia/Tehran',
        defaults={
            'id': uuid.uuid4(),
            'name': 'Tehran',
            'utc_offset': '+03:30',
            'display_name': 'تهران (UTC+03:30)',
            'is_active': True,
            'is_default': True,
            'order': 1
        }
    )
    
    # تبدیل داده‌های موجود
    for user in User.objects.all():
        # تبدیل language
        if user.language == 'fa':
            user.language_fk = fa_lang
        elif user.language == 'en':
            user.language_fk = en_lang
        else:
            user.language_fk = fa_lang  # پیش‌فرض
        
        # تبدیل timezone - همه به تهران
        user.timezone_fk = tehran_tz
        
        user.save(update_fields=['language_fk', 'timezone_fk'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_language_timezone_models'),
        ('accounts', '0004_add_temp_language_timezone_fields'),
    ]

    operations = [
        migrations.RunPython(
            create_and_populate_languages_timezones,
            migrations.RunPython.noop
        ),
    ]
