# Generated by Django 4.2.7 on 2025-12-21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_populate_language_timezone_data'),
    ]

    operations = [
        # حذف فیلدهای قدیمی
        migrations.RemoveField(
            model_name='user',
            name='language',
        ),
        migrations.RemoveField(
            model_name='user',
            name='timezone',
        ),
    ]
