# Generated by Django 4.2.7 on 2025-11-16 08:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_auditlog_options_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='کلید API'),
        ),
        migrations.AlterField(
            model_name='user',
            name='api_key_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ایجاد کلید API'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='تصویر پروفایل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='backup_codes',
            field=models.JSONField(blank=True, default=list, verbose_name='کدهای پشتیبان'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='بیوگرافی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='chat_context',
            field=models.JSONField(blank=True, default=dict, help_text='تنظیمات و زمینه کاربر برای تعاملات چت', verbose_name='زمینه گفتگو'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='نام شرکت'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(default='IRR', max_length=3, verbose_name='واحد پول'),
        ),
        migrations.AlterField(
            model_name='user',
            name='economic_code',
            field=models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator(message='Enter a valid 14-digit economic code.', regex='^\\d{14}$')], verbose_name='کد اقتصادی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True, verbose_name='اعلان\u200cهای ایمیل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='ایمیل تایید شده'),
        ),
        migrations.AlterField(
            model_name='user',
            name='failed_login_attempts',
            field=models.IntegerField(default=0, verbose_name='تلاش\u200cهای ناموفق ورود'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('fa', 'فارسی'), ('en', 'انگلیسی')], default='fa', max_length=5, verbose_name='زبان'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_password_change',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین تغییر رمز عبور'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین بازدید'),
        ),
        migrations.AlterField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='قفل تا'),
        ),
        migrations.AlterField(
            model_name='user',
            name='max_concurrent_sessions',
            field=models.IntegerField(default=3, verbose_name='حداکثر نشست\u200cهای همزمان'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit national ID.', regex='^\\d{10}$')], verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_id_verified',
            field=models.BooleanField(default=False, verbose_name='کد ملی تایید شده'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.organization', verbose_name='سازمان'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization_role',
            field=models.CharField(blank=True, choices=[('owner', 'مالک'), ('admin', 'مدیر'), ('member', 'عضو')], max_length=20, verbose_name='نقش در سازمان'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Iranian phone number.', regex='^(\\+98|0)?9\\d{9}$')], verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False, verbose_name='موبایل تایید شده'),
        ),
        migrations.AlterField(
            model_name='user',
            name='push_notifications',
            field=models.BooleanField(default=True, verbose_name='اعلان\u200cهای پوش'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sms_notifications',
            field=models.BooleanField(default=True, verbose_name='اعلان\u200cهای پیامکی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='Asia/Tehran', max_length=50, verbose_name='منطقه زمانی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=32, verbose_name='کلید TOTP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, verbose_name='احراز هویت دو مرحله\u200cای فعال'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('individual', 'فردی'), ('business', 'تجاری')], default='individual', max_length=20, verbose_name='نوع کاربر'),
        ),
    ]
