# Generated by Django 4.2.7 on 2025-12-21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_language_timezone_models'),
        ('accounts', '0006_remove_old_language_timezone_fields'),
    ]

    operations = [
        # تغییر نام فیلدهای موقت به نام اصلی
        migrations.RenameField(
            model_name='user',
            old_name='language_fk',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='timezone_fk',
            new_name='timezone',
        ),
        
        # تنظیم related_name و verbose_name صحیح
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.ForeignKey(
                blank=True, 
                null=True, 
                on_delete=django.db.models.deletion.SET_NULL, 
                related_name='users', 
                to='core.language', 
                verbose_name='زبان'
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.ForeignKey(
                blank=True, 
                null=True, 
                on_delete=django.db.models.deletion.SET_NULL, 
                related_name='users', 
                to='core.timezone', 
                verbose_name='منطقه زمانی'
            ),
        ),
    ]
