# Generated by Django 4.2.7 on 2025-11-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_api_key_alter_user_api_key_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, help_text='تنظیمات UI، تم، و سفارشی\u200cسازی پاسخ', verbose_name='تنظیمات کاربر'),
        ),
    ]
