# Generated by Django 4.2.7 on 2025-12-29 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_sms_signature'),
        ('accounts', '0007_rename_language_timezone_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.ForeignKey(blank=True, help_text='منطقه زمانی برای نمایش تاریخ و زمان (پیش\u200cفرض: تهران)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.timezone', verbose_name='منطقه زمانی'),
        ),
    ]
