# Generated by Django 4.2.7 on 2025-12-07 10:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_organizations', to=settings.AUTH_USER_MODEL, verbose_name='مالک'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='نام حقوقی شرکت'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='economic_code',
            field=models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator(message='لطفا یک کد اقتصادی 14 رقمی معتبر وارد کنید.', regex='^\\d{14}$')], verbose_name='Economic Code'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نام سازمان'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='لطفا یک شماره تلفن معتبر ایرانی وارد کنید (موبایل: 09123456789 یا ثابت: 02112345678)', regex='^(\\+98|0)?(\\d{10}|\\d{11})$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='economic_code',
            field=models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator(message='لطفا یک کد اقتصادی 14 رقمی معتبر وارد کنید.', regex='^\\d{14}$')], verbose_name='کد اقتصادی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='لطفا یک کد ملی 10 رقمی معتبر وارد کنید.', regex='^\\d{10}$')], verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization_role',
            field=models.CharField(blank=True, choices=[('admin', 'مدیر'), ('member', 'عضو')], max_length=20, verbose_name='نقش در سازمان'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='لطفا یک شماره تلفن معتبر ایرانی وارد کنید (موبایل: 09123456789 یا ثابت: 02112345678)', regex='^(\\+98|0)?(\\d{10}|\\d{11})$')], verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('individual', 'حقیقی'), ('business', 'حقوقی')], default='individual', max_length=20, verbose_name='نوع کاربر'),
        ),
    ]
