# Generated by Django 4.2.7 on 2025-12-07 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_organization_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='لطفا یک شماره تلفن معتبر ایرانی وارد کنید (موبایل: 09123456789 یا ثابت: 02112345678)', regex='^(\\+98|0)?(\\d{10}|\\d{11})$')], verbose_name='شماره موبایل'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('user_type', 'individual')), fields=('phone_number',), name='unique_phone_for_individual_users'),
        ),
    ]
