# Generated by Django 4.2.7 on 2025-12-09 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('accounts', '0009_phone_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_currency',
            field=models.ForeignKey(blank=True, help_text='ارز مورد نظر برای نمایش قیمت\u200cها (پیش\u200cفرض: تومان)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by_users', to='core.currency', verbose_name='ارز ترجیحی'),
        ),
    ]
