# Generated by Django 4.2.7 on 2025-12-18 11:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_preferred_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام گروه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('can_view_users', models.BooleanField(default=False, verbose_name='مشاهده کاربران')),
                ('can_edit_users', models.BooleanField(default=False, verbose_name='ویرایش کاربران')),
                ('can_delete_users', models.BooleanField(default=False, verbose_name='حذف کاربران')),
                ('can_view_financial', models.BooleanField(default=False, verbose_name='مشاهده امور مالی')),
                ('can_manage_financial', models.BooleanField(default=False, verbose_name='مدیریت امور مالی')),
                ('can_view_analytics', models.BooleanField(default=False, verbose_name='مشاهده گزارشات')),
                ('can_export_data', models.BooleanField(default=False, verbose_name='خروجی داده')),
                ('can_manage_content', models.BooleanField(default=False, verbose_name='مدیریت محتوا')),
                ('can_manage_subscriptions', models.BooleanField(default=False, verbose_name='مدیریت اشتراک\u200cها')),
                ('can_view_logs', models.BooleanField(default=False, verbose_name='مشاهده لاگ\u200cها')),
                ('can_manage_support', models.BooleanField(default=False, verbose_name='مدیریت پشتیبانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('priority', models.IntegerField(default=0, verbose_name='اولویت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'گروه کارمندی',
                'verbose_name_plural': 'گروه\u200cهای کارمندی',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='organization_role',
            field=models.CharField(blank=True, choices=[('owner', 'مالک'), ('admin', 'مدیر'), ('member', 'عضو')], max_length=20, verbose_name='نقش در سازمان'),
        ),
        migrations.AddField(
            model_name='user',
            name='staff_groups',
            field=models.ManyToManyField(blank=True, help_text='فقط برای کارمندان (is_staff=True) استفاده می\u200cشود', related_name='members', to='accounts.staffgroup', verbose_name='گروه\u200cهای کارمندی'),
        ),
    ]
