# Generated by Django 4.2.7 on 2025-12-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0011_staffgroup_alter_user_organization_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffgroup',
            name='can_delete_users',
        ),
        migrations.RemoveField(
            model_name='staffgroup',
            name='can_edit_users',
        ),
        migrations.RemoveField(
            model_name='staffgroup',
            name='can_export_data',
        ),
        migrations.RemoveField(
            model_name='staffgroup',
            name='can_manage_content',
        ),
        migrations.RemoveField(
            model_name='staffgroup',
            name='can_manage_financial',
        ),
        migrations.RemoveField(
            model_name='staffgroup',
            name='can_manage_subscriptions',
        ),
        migrations.RemoveField(
            model_name='staffgroup',
            name='can_manage_support',
        ),
        migrations.RemoveField(
            model_name='staffgroup',
            name='can_view_analytics',
        ),
        migrations.RemoveField(
            model_name='staffgroup',
            name='can_view_financial',
        ),
        migrations.RemoveField(
            model_name='staffgroup',
            name='can_view_logs',
        ),
        migrations.RemoveField(
            model_name='staffgroup',
            name='can_view_users',
        ),
        migrations.AddField(
            model_name='staffgroup',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='دسترسی\u200cهای این گروه کارمندی', to='auth.permission', verbose_name='دسترسی\u200cها'),
        ),
    ]
