# Generated by Django 4.2.7 on 2025-11-08 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='notification_preferences', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='ایمیل فعال')),
                ('sms_enabled', models.BooleanField(default=True, verbose_name='پیامک فعال')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='Push فعال')),
                ('in_app_enabled', models.BooleanField(default=True, verbose_name='داخل برنامه فعال')),
                ('system_notifications', models.BooleanField(default=True, verbose_name='اعلان\u200cهای سیستمی')),
                ('payment_notifications', models.BooleanField(default=True, verbose_name='اعلان\u200cهای پرداخت')),
                ('subscription_notifications', models.BooleanField(default=True, verbose_name='اعلان\u200cهای اشتراک')),
                ('chat_notifications', models.BooleanField(default=True, verbose_name='اعلان\u200cهای چت')),
                ('account_notifications', models.BooleanField(default=True, verbose_name='اعلان\u200cهای حساب')),
                ('security_notifications', models.BooleanField(default=True, verbose_name='اعلان\u200cهای امنیتی')),
                ('marketing_notifications', models.BooleanField(default=False, verbose_name='اعلان\u200cهای بازاریابی')),
                ('support_notifications', models.BooleanField(default=True, verbose_name='اعلان\u200cهای پشتیبانی')),
                ('quiet_hours_enabled', models.BooleanField(default=False, help_text='عدم ارسال اعلان در ساعات خاص', verbose_name='ساعات سکوت فعال')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='شروع ساعات سکوت')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='پایان ساعات سکوت')),
                ('digest_enabled', models.BooleanField(default=False, help_text='ارسال اعلان\u200cها به صورت خلاصه روزانه', verbose_name='خلاصه اعلان\u200cها')),
                ('digest_time', models.TimeField(blank=True, null=True, verbose_name='زمان ارسال خلاصه')),
                ('custom_preferences', models.JSONField(blank=True, default=dict, verbose_name='تنظیمات سفارشی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات اعلان',
                'verbose_name_plural': 'تنظیمات اعلان\u200cرسانی',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='مثال: payment_success, subscription_expired', max_length=100, unique=True, verbose_name='کد قالب')),
                ('name', models.CharField(max_length=200, verbose_name='نام قالب')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('category', models.CharField(choices=[('system', 'سیستم'), ('payment', 'پرداخت'), ('subscription', 'اشتراک'), ('chat', 'چت'), ('account', 'حساب کاربری'), ('security', 'امنیت'), ('marketing', 'بازاریابی'), ('support', 'پشتیبانی')], default='system', max_length=20, verbose_name='دسته\u200cبندی')),
                ('title_template', models.CharField(help_text='می\u200cتوانید از متغیرها استفاده کنید: {{user_name}}, {{amount}}, ...', max_length=200, verbose_name='قالب عنوان')),
                ('body_template', models.TextField(help_text='می\u200cتوانید از متغیرها استفاده کنید', verbose_name='قالب متن')),
                ('email_subject_template', models.CharField(blank=True, max_length=200, verbose_name='قالب موضوع ایمیل')),
                ('email_html_template', models.TextField(blank=True, verbose_name='قالب HTML ایمیل')),
                ('sms_template', models.CharField(blank=True, help_text='محدودیت 500 کاراکتر', max_length=500, verbose_name='قالب پیامک')),
                ('channels', models.JSONField(default=list, help_text='لیست کانال\u200cهای فعال: ["email", "sms", "push", "in_app"]', verbose_name='کانال\u200cهای ارسال')),
                ('default_priority', models.CharField(choices=[('low', 'پایین'), ('normal', 'عادی'), ('high', 'بالا'), ('urgent', 'فوری')], default='normal', max_length=10, verbose_name='اولویت پیش\u200cفرض')),
                ('action_url', models.CharField(blank=True, help_text='لینکی که کاربر با کلیک به آن هدایت می\u200cشود', max_length=500, verbose_name='URL اقدام')),
                ('action_text', models.CharField(blank=True, max_length=100, verbose_name='متن دکمه اقدام')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('require_confirmation', models.BooleanField(default=False, help_text='آیا کاربر باید تایید کند که این اعلان را دریافت کرده؟', verbose_name='نیاز به تایید')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='متادیتا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'قالب اعلان',
                'verbose_name_plural': 'قالب\u200cهای اعلان',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('body', models.TextField(verbose_name='متن')),
                ('category', models.CharField(choices=[('system', 'سیستم'), ('payment', 'پرداخت'), ('subscription', 'اشتراک'), ('chat', 'چت'), ('account', 'حساب کاربری'), ('security', 'امنیت'), ('marketing', 'بازاریابی'), ('support', 'پشتیبانی')], default='system', max_length=20, verbose_name='دسته\u200cبندی')),
                ('priority', models.CharField(choices=[('low', 'پایین'), ('normal', 'عادی'), ('high', 'بالا'), ('urgent', 'فوری')], default='normal', max_length=10, verbose_name='اولویت')),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name='لینک اقدام')),
                ('action_text', models.CharField(blank=True, max_length=100, verbose_name='متن دکمه')),
                ('channels', models.JSONField(default=list, verbose_name='کانال\u200cهای ارسال')),
                ('sent_via_email', models.BooleanField(default=False, verbose_name='ارسال شده از ایمیل')),
                ('sent_via_sms', models.BooleanField(default=False, verbose_name='ارسال شده از پیامک')),
                ('sent_via_push', models.BooleanField(default=False, verbose_name='ارسال شده از Push')),
                ('sent_via_in_app', models.BooleanField(default=True, verbose_name='ارسال شده در برنامه')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان خواندن')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تایید')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='متادیتا')),
                ('error_log', models.JSONField(blank=True, default=dict, verbose_name='لاگ خطاها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان انقضا')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationtemplate', verbose_name='قالب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=500, unique=True, verbose_name='توکن دستگاه')),
                ('device_type', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=10, verbose_name='نوع دستگاه')),
                ('device_name', models.CharField(blank=True, max_length=100, verbose_name='نام دستگاه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین استفاده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'توکن دستگاه',
                'verbose_name_plural': 'توکن\u200cهای دستگاه',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'ایمیل'), ('sms', 'پیامک'), ('push', 'Push Notification'), ('in_app', 'داخل برنامه'), ('websocket', 'WebSocket')], max_length=20, verbose_name='کانال')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('sent', 'ارسال شده'), ('delivered', 'تحویل داده شده'), ('failed', 'ناموفق'), ('bounced', 'برگشت خورده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('recipient', models.CharField(help_text='ایمیل، شماره تلفن، یا توکن دستگاه', max_length=255, verbose_name='گیرنده')),
                ('provider_response', models.JSONField(blank=True, default=dict, verbose_name='پاسخ سرویس\u200cدهنده')),
                ('provider_message_id', models.CharField(blank=True, max_length=255, verbose_name='شناسه پیام نزد سرویس\u200cدهنده')),
                ('error_message', models.TextField(blank=True, verbose_name='پیام خطا')),
                ('retry_count', models.IntegerField(default=0, verbose_name='تعداد تلاش مجدد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تحویل')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notification', verbose_name='اعلان')),
            ],
            options={
                'verbose_name': 'لاگ اعلان',
                'verbose_name_plural': 'لاگ اعلان\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['notification', 'channel'], name='notificatio_notific_9169c3_idx'), models.Index(fields=['status', 'created_at'], name='notificatio_status_68c9bc_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='notificatio_user_id_8a7c6b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['category', 'created_at'], name='notificatio_categor_e0e064_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['-created_at'], name='notificatio_created_ae6ed6_idx'),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['user', 'is_active'], name='notificatio_user_id_f0e72c_idx'),
        ),
    ]
