# Generated by Django 4.2.7 on 2025-12-20 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpreference',
            name='custom_preferences',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='digest_enabled',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='digest_time',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='quiet_hours_enabled',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='quiet_hours_end',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='quiet_hours_start',
        ),
    ]
