# Generated by Django 4.2.7 on 2025-12-19 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rag_conversation_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.CharField(default='گفتگوی جدید', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('default_response_mode', models.CharField(choices=[('simple_explanation', 'توضیح ساده'), ('legal_reference', 'ارجاع قانونی دقیق'), ('action_checklist', 'چک\u200cلیست اقدام')], default='simple_explanation', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_shared', models.BooleanField(default=False)),
                ('share_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('message_count', models.IntegerField(default=0)),
                ('token_usage', models.IntegerField(default=0)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'گفتگو',
                'verbose_name_plural': 'گفتگوها',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rag_message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('role', models.CharField(choices=[('user', 'کاربر'), ('assistant', 'دستیار'), ('system', 'سیستم')], max_length=20)),
                ('content', models.TextField()),
                ('response_mode', models.CharField(blank=True, choices=[('simple_explanation', 'توضیح ساده'), ('legal_reference', 'ارجاع قانونی دقیق'), ('action_checklist', 'چک\u200cلیست اقدام')], max_length=20)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('chunks', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('processing', 'در حال پردازش'), ('completed', 'تکمیل شده'), ('failed', 'خطا')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('tokens', models.IntegerField(default=0)),
                ('processing_time_ms', models.IntegerField(default=0)),
                ('model_used', models.CharField(blank=True, max_length=50)),
                ('cached', models.BooleanField(default=False)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('feedback_type', models.CharField(blank=True, max_length=50)),
                ('feedback_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام\u200cها',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_token', models.CharField(max_length=64, unique=True)),
                ('allow_copy', models.BooleanField(default=True)),
                ('allow_export', models.BooleanField(default=False)),
                ('password_protected', models.BooleanField(default=False)),
                ('password_hash', models.CharField(blank=True, max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_views', models.IntegerField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='chat.conversation')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'گفتگوی اشتراکی',
                'verbose_name_plural': 'گفتگوهای اشتراکی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=500)),
                ('file_size', models.IntegerField()),
                ('file_type', models.CharField(choices=[('document', 'سند'), ('image', 'تصویر'), ('pdf', 'PDF'), ('spreadsheet', 'صفحه گسترده')], max_length=20)),
                ('mime_type', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='chat/thumbnails/%Y/%m/')),
                ('extracted_text', models.TextField(blank=True)),
                ('extraction_status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.message')),
            ],
            options={
                'verbose_name': 'پیوست پیام',
                'verbose_name_plural': 'پیوست\u200cهای پیام',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('icon', models.CharField(default='folder', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='chat.conversationfolder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پوشه گفتگو',
                'verbose_name_plural': 'پوشه\u200cهای گفتگو',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.conversationfolder'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ChatTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('legal', 'حقوقی'), ('business', 'کسب\u200cوکار'), ('tax', 'مالیاتی'), ('insurance', 'بیمه'), ('labor', 'کار و استخدام'), ('contract', 'قراردادها')], max_length=20)),
                ('prompt_template', models.TextField()),
                ('variables', models.JSONField(default=list)),
                ('icon', models.CharField(default='template', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'قالب چت',
                'verbose_name_plural': 'قالب\u200cهای چت',
                'ordering': ['-usage_count', 'category', 'title'],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='chat_messag_convers_3154fc_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['rag_message_id'], name='chat_messag_rag_mes_5de802_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversationfolder',
            unique_together={('user', 'name', 'parent')},
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', '-last_message_at'], name='chat_conver_user_id_539cc6_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['rag_conversation_id'], name='chat_conver_rag_con_470eff_idx'),
        ),
    ]
