# Generated by Django 4.2.7 on 2025-12-19 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='نام پلن')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('plan_type', models.CharField(choices=[('individual', 'حقیقی'), ('business', 'حقوقی')], default='individual', max_length=20, verbose_name='نوع پلن')),
                ('price', models.DecimalField(decimal_places=0, help_text='قیمت به ارز پایه سایت', max_digits=15, verbose_name='قیمت')),
                ('duration_days', models.IntegerField(default=30, verbose_name='مدت به روز')),
                ('max_queries_per_day', models.IntegerField(default=10, verbose_name='سوال/روز')),
                ('max_queries_per_month', models.IntegerField(default=300, verbose_name='سوال/ماه')),
                ('max_active_sessions', models.IntegerField(default=3, help_text='حداکثر تعداد دستگاه\u200cهای همزمان', verbose_name='حداکثر جلسات فعال')),
                ('max_organization_members', models.IntegerField(default=1, help_text='فقط برای پلن\u200cهای حقوقی', verbose_name='حداکثر اعضای سازمان')),
                ('features', models.JSONField(blank=True, default=dict, verbose_name='ویژگی\u200cها')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'پلن',
                'verbose_name_plural': 'پلن\u200cها',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'فعال'), ('expired', 'منقضی شده'), ('cancelled', 'لغو شده'), ('pending', 'در انتظار')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(verbose_name='تاریخ پایان')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='تمدید خودکار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan', verbose_name='پلن')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اشتراک کاربر',
                'verbose_name_plural': 'اشتراک کاربران',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserUsageReport',
            fields=[
            ],
            options={
                'verbose_name': 'گزارش مصرف کاربر',
                'verbose_name_plural': 'گزارش مصرف کاربران',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('subscriptions.subscription',),
        ),
        migrations.CreateModel(
            name='ModelUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('query', 'سوال'), ('file_upload', 'آپلود فایل'), ('file_download', 'دانلود فایل'), ('api_call', 'فراخوانی API')], default='query', max_length=20, verbose_name='نوع عملیات')),
                ('input_tokens', models.IntegerField(default=0, verbose_name='توکن ورودی')),
                ('output_tokens', models.IntegerField(default=0, verbose_name='توکن خروجی')),
                ('plan_name', models.CharField(blank=True, help_text='نام پلن در زمان ثبت لاگ', max_length=100, verbose_name='نام پلن')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='اطلاعات اضافی مثل model_used, conversation_id, etc.', verbose_name='متادیتا')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_usage_logs', to='subscriptions.subscription', verbose_name='اشتراک')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_usage_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'گزارش مصرف مدل',
                'verbose_name_plural': 'گزارش مصرف مدل\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'action_type', 'created_at'], name='subscriptio_user_id_8b6dae_idx'), models.Index(fields=['subscription', 'created_at'], name='subscriptio_subscri_549ade_idx'), models.Index(fields=['created_at'], name='subscriptio_created_397220_idx')],
            },
        ),
    ]
