# Generated by Django 4.2.7 on 2025-12-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='max_queries_per_month',
            field=models.IntegerField(default=200, verbose_name='سوال/ماه'),
        ),
    ]
