# Generated by Django 4.2.7 on 2025-12-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_add_usage_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_queries_per_day',
            field=models.IntegerField(default=10, verbose_name='سوال/روز'),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_queries_per_month',
            field=models.IntegerField(default=300, verbose_name='سوال/ماه'),
        ),
    ]
