# Generated by Django 4.2.7 on 2025-12-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_add_query_limits_to_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagelog',
            name='plan_name',
            field=models.CharField(blank=True, help_text='نام پلن در زمان ثبت لاگ', max_length=100, verbose_name='نام پلن'),
        ),
    ]
