# Generated by Django 4.2.7 on 2025-12-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_add_plan_name_to_usagelog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-created_at'], 'verbose_name': 'اشتراک کاربر', 'verbose_name_plural': 'اشتراک کاربران'},
        ),
        migrations.AlterModelOptions(
            name='usagelog',
            options={'ordering': ['-created_at'], 'verbose_name': 'لاگ کاربر', 'verbose_name_plural': 'لاگ کاربران'},
        ),
        migrations.AddField(
            model_name='plan',
            name='max_organization_members',
            field=models.IntegerField(default=1, help_text='فقط برای پلن\u200cهای حقوقی', verbose_name='حداکثر اعضای سازمان'),
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('individual', 'حقیقی'), ('business', 'حقوقی')], default='individual', max_length=20, verbose_name='نوع پلن'),
        ),
    ]
