# Generated by Django 4.2.7 on 2025-12-09 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('subscriptions', '0005_organization_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='ارز برای نمایش قیمت (پیش\u200cفرض: ارز پایه سایت)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='core.currency', verbose_name='ارز نمایش'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='قیمت (به واحد پایه)'),
        ),
    ]
