# Generated by Django 4.2.7 on 2025-12-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_plan_currency_alter_plan_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='currency',
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=0, help_text='قیمت به ارز پایه سایت', max_digits=15, verbose_name='قیمت'),
        ),
    ]
