# Generated by Django 4.2.7 on 2025-12-18 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0007_currency_base_and_plan_simplify'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('query', 'سوال'), ('file_upload', 'آپلود فایل'), ('file_download', 'دانلود فایل'), ('api_call', 'فراخوانی API')], default='query', max_length=20, verbose_name='نوع عملیات')),
                ('input_tokens', models.IntegerField(default=0, verbose_name='توکن ورودی')),
                ('output_tokens', models.IntegerField(default=0, verbose_name='توکن خروجی')),
                ('plan_name', models.CharField(blank=True, help_text='نام پلن در زمان ثبت لاگ', max_length=100, verbose_name='نام پلن')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='اطلاعات اضافی مثل model_used, conversation_id, etc.', verbose_name='متادیتا')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_usage_logs', to='subscriptions.subscription', verbose_name='اشتراک')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_usage_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'گزارش مصرف مدل',
                'verbose_name_plural': 'گزارش مصرف مدل\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserUsageReport',
            fields=[
            ],
            options={
                'verbose_name': 'گزارش مصرف کاربر',
                'verbose_name_plural': 'گزارش مصرف کاربران',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('subscriptions.subscription',),
        ),
        migrations.DeleteModel(
            name='UsageLog',
        ),
        migrations.AddIndex(
            model_name='modelusagelog',
            index=models.Index(fields=['user', 'action_type', 'created_at'], name='subscriptio_user_id_8b6dae_idx'),
        ),
        migrations.AddIndex(
            model_name='modelusagelog',
            index=models.Index(fields=['subscription', 'created_at'], name='subscriptio_subscri_549ade_idx'),
        ),
        migrations.AddIndex(
            model_name='modelusagelog',
            index=models.Index(fields=['created_at'], name='subscriptio_created_397220_idx'),
        ),
    ]
