# Generated by Django 4.2.7 on 2025-12-19 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='analytics', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('total_queries', models.IntegerField(default=0, verbose_name='کل کوئری\u200cها')),
                ('total_tokens', models.BigIntegerField(default=0, verbose_name='کل توکن\u200cها')),
                ('total_conversations', models.IntegerField(default=0, verbose_name='کل مکالمات')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='کل هزینه')),
                ('last_query_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین کوئری')),
                ('last_payment_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین پرداخت')),
                ('active_days', models.IntegerField(default=0, verbose_name='روزهای فعال')),
                ('avg_queries_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='میانگین کوئری روزانه')),
                ('avg_tokens_per_query', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='میانگین توکن هر کوئری')),
                ('avg_response_time', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='میانگین زمان پاسخ (ثانیه)')),
                ('engagement_score', models.IntegerField(default=0, help_text='0-100', verbose_name='امتیاز تعامل')),
                ('value_score', models.IntegerField(default=0, help_text='0-100', verbose_name='امتیاز ارزش')),
                ('preferred_model', models.CharField(blank=True, max_length=50, verbose_name='مدل ترجیحی')),
                ('preferred_response_mode', models.CharField(blank=True, max_length=50, verbose_name='حالت پاسخ ترجیحی')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='متادیتا')),
                ('first_activity', models.DateTimeField(blank=True, null=True, verbose_name='اولین فعالیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تحلیل کاربر',
                'verbose_name_plural': 'تحلیل کاربران',
            },
        ),
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='زمان')),
                ('cpu_usage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='مصرف CPU (%)')),
                ('memory_usage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='مصرف RAM (%)')),
                ('disk_usage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='مصرف دیسک (%)')),
                ('active_connections', models.IntegerField(default=0, verbose_name='اتصالات فعال')),
                ('request_per_second', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='درخواست در ثانیه')),
                ('avg_response_time', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='میانگین زمان پاسخ (ms)')),
                ('error_count', models.IntegerField(default=0, verbose_name='تعداد خطا')),
                ('error_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نرخ خطا (%)')),
                ('queue_size', models.IntegerField(default=0, verbose_name='اندازه صف')),
                ('queue_processing_time', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='زمان پردازش صف (ms)')),
                ('cache_hit_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نرخ Cache Hit (%)')),
            ],
            options={
                'verbose_name': 'متریک سیستم',
                'verbose_name_plural': 'متریک\u200cهای سیستم',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='analytics_s_timesta_058647_idx')],
            },
        ),
        migrations.CreateModel(
            name='RevenueAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_type', models.CharField(choices=[('daily', 'روزانه'), ('weekly', 'هفتگی'), ('monthly', 'ماهانه'), ('quarterly', 'فصلی'), ('yearly', 'سالانه')], max_length=20, verbose_name='نوع دوره')),
                ('period_start', models.DateField(verbose_name='شروع دوره')),
                ('period_end', models.DateField(verbose_name='پایان دوره')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='کل درآمد')),
                ('subscription_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='درآمد اشتراک')),
                ('one_time_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='درآمد یکباره')),
                ('total_transactions', models.IntegerField(default=0, verbose_name='کل تراکنش\u200cها')),
                ('successful_transactions', models.IntegerField(default=0, verbose_name='تراکنش\u200cهای موفق')),
                ('failed_transactions', models.IntegerField(default=0, verbose_name='تراکنش\u200cهای ناموفق')),
                ('new_customers', models.IntegerField(default=0, verbose_name='مشتریان جدید')),
                ('returning_customers', models.IntegerField(default=0, verbose_name='مشتریان بازگشتی')),
                ('avg_transaction_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='میانگین ارزش تراکنش')),
                ('avg_customer_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='میانگین ارزش مشتری')),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نرخ تبدیل (%)')),
                ('churn_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نرخ ریزش (%)')),
                ('growth_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نرخ رشد (%)')),
                ('gateway_breakdown', models.JSONField(default=dict, verbose_name='تفکیک درگاه\u200cها')),
                ('plan_breakdown', models.JSONField(default=dict, verbose_name='تفکیک پلن\u200cها')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='متادیتا')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تحلیل درآمد',
                'verbose_name_plural': 'تحلیل\u200cهای درآمد',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['period_type', 'period_start'], name='analytics_r_period__36cde2_idx')],
                'unique_together': {('period_type', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, verbose_name='تاریخ')),
                ('metric_type', models.CharField(choices=[('user_registration', 'ثبت\u200cنام کاربران'), ('user_login', 'ورود کاربران'), ('query_count', 'تعداد کوئری'), ('token_usage', 'مصرف توکن'), ('revenue', 'درآمد'), ('subscription', 'اشتراک'), ('payment', 'پرداخت'), ('api_usage', 'استفاده از API'), ('error_rate', 'نرخ خطا'), ('response_time', 'زمان پاسخ')], db_index=True, max_length=30, verbose_name='نوع متریک')),
                ('count', models.IntegerField(default=0, verbose_name='تعداد')),
                ('sum_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مجموع')),
                ('avg_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='میانگین')),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='حداقل')),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='حداکثر')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='متادیتا')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'متریک روزانه',
                'verbose_name_plural': 'متریک\u200cهای روزانه',
                'ordering': ['-date', 'metric_type'],
                'indexes': [models.Index(fields=['date', 'metric_type'], name='analytics_d_date_576223_idx')],
                'unique_together': {('date', 'metric_type')},
            },
        ),
    ]
