# Generated by Django 4.2.7 on 2025-12-19 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='default_payment_gateway',
        ),
    ]
