# Generated by Django 4.2.7 on 2025-12-19 12:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='کد ارز')),
                ('name', models.CharField(max_length=50, verbose_name='نام ارز')),
                ('symbol', models.CharField(max_length=10, verbose_name='نماد')),
                ('has_decimals', models.BooleanField(default=False, verbose_name='دارای اعشار')),
                ('decimal_places', models.PositiveSmallIntegerField(default=0, help_text='تعداد ارقام اعشار (0 برای تومان/ریال، 2 برای دلار)', verbose_name='تعداد ارقام اعشار')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, help_text='نرخ تبدیل این ارز به واحد پایه سایت (1 = واحد پایه)', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='نرخ تبدیل به واحد پایه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_base', models.BooleanField(default=False, help_text='فقط یک ارز می\u200cتواند ارز پایه باشد. قیمت\u200cها به این ارز ذخیره می\u200cشوند.', verbose_name='ارز پایه')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ارز',
                'verbose_name_plural': 'ارزها',
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='شماره فاکتور')),
                ('buyer_name', models.CharField(max_length=255, verbose_name='نام خریدار')),
                ('buyer_national_id', models.CharField(blank=True, max_length=20, verbose_name='کد ملی/شناسه ملی')),
                ('buyer_economic_code', models.CharField(blank=True, max_length=20, verbose_name='کد اقتصادی خریدار')),
                ('buyer_address', models.TextField(blank=True, verbose_name='آدرس خریدار')),
                ('buyer_postal_code', models.CharField(blank=True, max_length=20, verbose_name='کد پستی خریدار')),
                ('buyer_phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن خریدار')),
                ('is_legal_buyer', models.BooleanField(default=False, verbose_name='خریدار حقوقی')),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='جمع قبل از مالیات')),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='درصد مالیات')),
                ('tax_amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ مالیات')),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='تخفیف')),
                ('total', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='جمع کل')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('issued', 'صادر شده'), ('paid', 'پرداخت شده'), ('cancelled', 'لغو شده'), ('sent_to_tax', 'ارسال به مالیات'), ('tax_confirmed', 'تایید مالیات'), ('tax_rejected', 'رد مالیات')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('invoice_type', models.CharField(choices=[('sale', 'فروش'), ('return', 'برگشت از فروش')], default='sale', max_length=20, verbose_name='نوع فاکتور')),
                ('tax_id', models.CharField(blank=True, max_length=100, verbose_name='شناسه یکتای مالیاتی')),
                ('tax_serial', models.CharField(blank=True, max_length=100, verbose_name='سریال مالیاتی')),
                ('sent_to_tax_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال به مالیات')),
                ('tax_response', models.JSONField(blank=True, null=True, verbose_name='پاسخ سامانه مالیات')),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ صدور')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ سررسید')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.transaction', verbose_name='پرداخت مرتبط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='خریدار')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتورها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_type', models.CharField(choices=[('monthly', 'ماهانه'), ('quarterly', 'فصلی'), ('yearly', 'سالانه')], max_length=20, verbose_name='نوع دوره')),
                ('period_start', models.DateField(verbose_name='شروع دوره')),
                ('period_end', models.DateField(verbose_name='پایان دوره')),
                ('total_sales', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='کل فروش')),
                ('total_tax', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='کل مالیات')),
                ('invoice_count', models.PositiveIntegerField(default=0, verbose_name='تعداد فاکتور')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('submitted', 'ارسال شده'), ('confirmed', 'تایید شده'), ('rejected', 'رد شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'گزارش مالیاتی',
                'verbose_name_plural': 'گزارشات مالیاتی',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام درگاه')),
                ('connected_account', models.CharField(blank=True, max_length=50, verbose_name='شماره حساب متصل')),
                ('merchant_id', models.CharField(blank=True, max_length=255, verbose_name='شناسه پذیرنده')),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='کلید API')),
                ('api_secret', models.CharField(blank=True, max_length=255, verbose_name='رمز API')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_sandbox', models.BooleanField(default=False, verbose_name='حالت تست')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='درصد کارمزد')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supported_currencies', models.ManyToManyField(blank=True, related_name='payment_gateways', to='finance.currency', verbose_name='ارزهای پشتیبانی شده')),
            ],
            options={
                'verbose_name': 'درگاه پرداخت',
                'verbose_name_plural': 'درگاه\u200cهای پرداخت',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='شرح')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='قیمت واحد')),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='تخفیف')),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='درصد مالیات')),
                ('tax_amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ مالیات')),
                ('total', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='جمع')),
                ('service_code', models.CharField(blank=True, max_length=20, verbose_name='کد خدمات')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.invoice', verbose_name='فاکتور')),
            ],
            options={
                'verbose_name': 'آیتم فاکتور',
                'verbose_name_plural': 'آیتم\u200cهای فاکتور',
            },
        ),
        migrations.CreateModel(
            name='FinancialSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='تجارت چت', max_length=255, verbose_name='نام شرکت/فروشنده')),
                ('company_name_en', models.CharField(blank=True, max_length=255, verbose_name='نام انگلیسی شرکت')),
                ('company_address', models.TextField(blank=True, verbose_name='آدرس')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='کد پستی')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('fax', models.CharField(blank=True, max_length=20, verbose_name='فکس')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('website', models.URLField(blank=True, verbose_name='وب\u200cسایت')),
                ('economic_code', models.CharField(blank=True, max_length=20, verbose_name='کد اقتصادی')),
                ('national_id', models.CharField(blank=True, max_length=20, verbose_name='شناسه ملی')),
                ('registration_number', models.CharField(blank=True, max_length=20, verbose_name='شماره ثبت')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='درصد مالیات ارزش افزوده')),
                ('moadian_enabled', models.BooleanField(default=False, verbose_name='اتصال به سامانه مودیان')),
                ('moadian_api_key', models.CharField(blank=True, max_length=500, verbose_name='کلید API مودیان')),
                ('moadian_private_key', models.TextField(blank=True, verbose_name='کلید خصوصی مودیان')),
                ('moadian_memory_id', models.CharField(blank=True, max_length=100, verbose_name='شناسه حافظه مالیاتی')),
                ('moadian_fiscal_id', models.CharField(blank=True, max_length=100, verbose_name='شناسه یکتای مالیاتی')),
                ('auto_invoice_legal', models.BooleanField(default=True, verbose_name='صدور خودکار فاکتور برای حقوقی')),
                ('auto_invoice_all', models.BooleanField(default=False, verbose_name='صدور فاکتور برای همه')),
                ('invoice_prefix', models.CharField(default='INV', max_length=10, verbose_name='پیشوند شماره فاکتور')),
                ('invoice_start_number', models.PositiveIntegerField(default=1000, verbose_name='شماره شروع فاکتور')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_payment_gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_settings', to='finance.paymentgateway', verbose_name='درگاه پرداخت پیش\u200cفرض')),
            ],
            options={
                'verbose_name': 'تنظیمات مالی',
                'verbose_name_plural': 'تنظیمات مالی',
            },
        ),
    ]
