# Generated by Django 4.2.7 on 2025-12-19 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialsettings',
            name='economic_code',
        ),
        migrations.RemoveField(
            model_name='financialsettings',
            name='email',
        ),
        migrations.RemoveField(
            model_name='financialsettings',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='financialsettings',
            name='website',
        ),
    ]
