# Generated by Django 4.2.7 on 2025-12-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_unused_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgateway',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='درگاه پیش\u200cفرض'),
        ),
    ]
