# Generated by Django 4.2.7 on 2025-12-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_move_default_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='is_default',
            field=models.BooleanField(default=False, help_text='ارز پیش\u200cفرضی که برای کاربران جدید تنظیم می\u200cشود', verbose_name='ارز پیش\u200cفرض'),
        ),
    ]
