# Generated by Django 4.2.7 on 2025-12-29 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_add_is_default_to_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgateway',
            name='base_currency',
            field=models.ForeignKey(blank=True, help_text='ارزی که درگاه پرداخت مبالغ را بر اساس آن دریافت می\u200cکند', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='base_for_gateways', to='finance.currency', verbose_name='ارز مبنا'),
        ),
    ]
