# Generated by Django 4.2.7 on 2025-12-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_add_base_currency_to_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgateway',
            name='gateway_type',
            field=models.CharField(choices=[('zarinpal', 'زرین\u200cپال'), ('tejarat_test', 'درگاه تست تجارت'), ('plisio', 'Plisio'), ('other', 'سایر')], default='other', max_length=20, verbose_name='نوع درگاه'),
        ),
    ]
