# Generated by Django 4.2.7 on 2025-12-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_paymentgateway_gateway_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgateway',
            name='gateway_type',
            field=models.CharField(choices=[('zarinpal', 'زرین\u200cپال'), ('plisio', 'Plisio'), ('other', 'سایر')], default='other', max_length=20, verbose_name='نوع درگاه'),
        ),
    ]
