# Generated by Django 4.2.7 on 2025-12-29 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_paymentgateway_gateway_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='buyer_economic_code',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='due_date',
        ),
    ]
