# Generated by Django 4.2.7 on 2025-12-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_remove_invoice_buyer_economic_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='send_to_tax_system',
            field=models.BooleanField(default=True, verbose_name='ارسال به سامانه مالیاتی'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_response',
            field=models.JSONField(blank=True, null=True, verbose_name='پاسخ سامانه مالیاتی'),
        ),
    ]
