# Generated by Django 4.2.7 on 2025-12-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_invoice_send_to_tax_system_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'گزارش درآمد',
                'verbose_name_plural': 'گزارشات درآمد',
                'permissions': [('view_revenue_report', 'Can view revenue report')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
