# Generated by Django 4.2.7 on 2025-12-30 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_revenuereport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RevenueReport',
        ),
    ]
