# Generated by Django 4.2.7 on 2025-11-16 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_alter_user_managers_alter_user_email_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام نقش')),
                ('role_type', models.CharField(choices=[('super_admin', 'مدیر ارشد'), ('admin', 'مدیر'), ('moderator', 'ناظر'), ('support', 'پشتیبانی'), ('finance', 'مالی'), ('content', 'محتوا'), ('analyst', 'تحلیل\u200cگر'), ('custom', 'سفارشی')], default='custom', max_length=20, verbose_name='نوع نقش')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('can_view_all_users', models.BooleanField(default=False, verbose_name='مشاهده همه کاربران')),
                ('can_edit_users', models.BooleanField(default=False, verbose_name='ویرایش کاربران')),
                ('can_delete_users', models.BooleanField(default=False, verbose_name='حذف کاربران')),
                ('can_view_financial', models.BooleanField(default=False, verbose_name='مشاهده امور مالی')),
                ('can_manage_financial', models.BooleanField(default=False, verbose_name='مدیریت امور مالی')),
                ('can_view_analytics', models.BooleanField(default=False, verbose_name='مشاهده گزارشات')),
                ('can_export_data', models.BooleanField(default=False, verbose_name='خروجی داده')),
                ('can_manage_content', models.BooleanField(default=False, verbose_name='مدیریت محتوا')),
                ('can_manage_system', models.BooleanField(default=False, verbose_name='مدیریت سیستم')),
                ('can_view_logs', models.BooleanField(default=False, verbose_name='مشاهده لاگ\u200cها')),
                ('priority', models.IntegerField(default=0, verbose_name='اولویت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_default', models.BooleanField(default=False, verbose_name='پیش\u200cفرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_roles', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission', verbose_name='دسترسی\u200cها')),
            ],
            options={
                'verbose_name': 'نقش',
                'verbose_name_plural': 'نقش\u200cها',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='admin_profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='بخش/دپارتمان')),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='کد پرسنلی')),
                ('access_start_time', models.TimeField(blank=True, null=True, verbose_name='ساعت شروع دسترسی')),
                ('access_end_time', models.TimeField(blank=True, null=True, verbose_name='ساعت پایان دسترسی')),
                ('allowed_ips', models.TextField(blank=True, help_text='هر IP در یک خط', verbose_name='IP های مجاز')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('last_activity', models.DateTimeField(blank=True, null=True, verbose_name='آخرین فعالیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('roles', models.ManyToManyField(blank=True, to='admin_panel.role', verbose_name='نقش\u200cها')),
            ],
            options={
                'verbose_name': 'کاربر ادمین',
                'verbose_name_plural': 'کاربران ادمین',
            },
        ),
        migrations.CreateModel(
            name='AdminDashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('widget_type', models.CharField(choices=[('stats_card', 'کارت آمار'), ('chart_line', 'نمودار خطی'), ('chart_bar', 'نمودار میله\u200cای'), ('chart_pie', 'نمودار دایره\u200cای'), ('table', 'جدول'), ('activity_feed', 'فید فعالیت'), ('quick_actions', 'دسترسی سریع'), ('calendar', 'تقویم'), ('todo_list', 'لیست کارها')], max_length=20, verbose_name='نوع ویجت')),
                ('config', models.JSONField(default=dict, help_text='تنظیمات JSON ویجت', verbose_name='تنظیمات')),
                ('required_permission', models.CharField(blank=True, max_length=100, verbose_name='دسترسی مورد نیاز')),
                ('position_x', models.IntegerField(default=0, verbose_name='موقعیت X')),
                ('position_y', models.IntegerField(default=0, verbose_name='موقعیت Y')),
                ('width', models.IntegerField(default=3, verbose_name='عرض')),
                ('height', models.IntegerField(default=2, verbose_name='ارتفاع')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_default', models.BooleanField(default=False, verbose_name='پیش\u200cفرض')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roles', models.ManyToManyField(blank=True, to='admin_panel.role', verbose_name='نقش\u200cهای مجاز')),
            ],
            options={
                'verbose_name': 'ویجت داشبورد',
                'verbose_name_plural': 'ویجت\u200cهای داشبورد',
                'ordering': ['position_y', 'position_x'],
            },
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('broadcast', models.BooleanField(default=False, verbose_name='پخش عمومی')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='پیام')),
                ('notification_type', models.CharField(choices=[('info', 'اطلاعیه'), ('warning', 'هشدار'), ('error', 'خطا'), ('success', 'موفقیت'), ('critical', 'بحرانی')], default='info', max_length=20, verbose_name='نوع')),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name='لینک اقدام')),
                ('action_text', models.CharField(blank=True, max_length=100, verbose_name='متن دکمه اقدام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان خواندن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان انقضا')),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='admin_panel.adminuser', verbose_name='کاربر ادمین')),
                ('roles', models.ManyToManyField(blank=True, to='admin_panel.role', verbose_name='نقش\u200cهای گیرنده')),
            ],
            options={
                'verbose_name': 'اعلان ادمین',
                'verbose_name_plural': 'اعلان\u200cهای ادمین',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin_user', 'is_read', 'created_at'], name='admin_panel_admin_u_15e990_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('login', 'ورود'), ('logout', 'خروج'), ('view', 'مشاهده'), ('create', 'ایجاد'), ('update', 'به\u200cروزرسانی'), ('delete', 'حذف'), ('export', 'خروجی'), ('import', 'ورودی'), ('approve', 'تایید'), ('reject', 'رد'), ('block', 'مسدودسازی'), ('unblock', 'رفع مسدودی')], max_length=20, verbose_name='نوع عملیات')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='نام مدل')),
                ('object_id', models.CharField(blank=True, max_length=255, verbose_name='شناسه شیء')),
                ('object_repr', models.CharField(blank=True, max_length=500, verbose_name='نمایش شیء')),
                ('before_data', models.JSONField(blank=True, default=dict, verbose_name='داده قبلی')),
                ('after_data', models.JSONField(blank=True, default=dict, verbose_name='داده جدید')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='متادیتا')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان انجام')),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='admin_panel.adminuser', verbose_name='کاربر ادمین')),
            ],
            options={
                'verbose_name': 'لاگ عملیات ادمین',
                'verbose_name_plural': 'لاگ عملیات ادمین\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin_user', 'created_at'], name='admin_panel_admin_u_72b334_idx'), models.Index(fields=['action_type', 'created_at'], name='admin_panel_action__9e3e2b_idx'), models.Index(fields=['model_name', 'object_id'], name='admin_panel_model_n_c82b15_idx')],
            },
        ),
    ]
