# Generated by Django 4.2.7 on 2025-11-08 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_id', models.CharField(help_text='شناسه مرجع تراکنش', max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ')),
                ('currency', models.CharField(default='IRR', help_text='ISO 4217 currency code', max_length=3, verbose_name='ارز')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='نرخ تبدیل')),
                ('gateway', models.CharField(choices=[('zarinpal', 'زرین\u200cپال'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('crypto', 'Cryptocurrency'), ('bank_transfer', 'انتقال بانکی'), ('credit', 'اعتبار حساب')], max_length=20, verbose_name='درگاه پرداخت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('processing', 'در حال پردازش'), ('success', 'موفق'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده'), ('refunded', 'بازگشت داده شده'), ('partially_refunded', 'بازگشت جزئی')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=255, verbose_name='شناسه تراکنش درگاه')),
                ('gateway_response', models.JSONField(blank=True, default=dict, verbose_name='پاسخ درگاه')),
                ('discount_code', models.CharField(blank=True, max_length=50, verbose_name='کد تخفیف')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبلغ تخفیف')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مالیات')),
                ('invoice_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='شماره فاکتور')),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='invoices/%Y/%m/', verbose_name='فایل فاکتور')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت داخلی')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='متادیتا')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بازگشت')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.plan', verbose_name='پلن')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='subscriptions.subscription', verbose_name='اشتراک')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='موجودی')),
                ('currency', models.CharField(default='IRR', max_length=3, verbose_name='ارز')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کیف پول',
                'verbose_name_plural': 'کیف پول\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ZarinpalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority', models.CharField(max_length=100, unique=True, verbose_name='Authority')),
                ('card_hash', models.CharField(blank=True, max_length=255, verbose_name='هش کارت')),
                ('card_pan', models.CharField(blank=True, max_length=20, verbose_name='شماره کارت')),
                ('ref_id', models.CharField(blank=True, max_length=100, verbose_name='Ref ID')),
                ('fee_type', models.CharField(blank=True, max_length=20, verbose_name='نوع کارمزد')),
                ('fee', models.IntegerField(default=0, verbose_name='کارمزد')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zarinpal_payment', to='payments.transaction')),
            ],
            options={
                'verbose_name': 'پرداخت زرین\u200cپال',
                'verbose_name_plural': 'پرداخت\u200cهای زرین\u200cپال',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('credit', 'واریز'), ('debit', 'برداشت')], max_length=10, verbose_name='نوع تراکنش')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='موجودی پس از تراکنش')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.transaction', verbose_name='تراکنش مرتبط')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.wallet', verbose_name='کیف پول')),
            ],
            options={
                'verbose_name': 'تراکنش کیف پول',
                'verbose_name_plural': 'تراکنش\u200cهای کیف پول',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StripePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_intent_id', models.CharField(max_length=255, unique=True, verbose_name='Payment Intent ID')),
                ('charge_id', models.CharField(blank=True, max_length=255, verbose_name='Charge ID')),
                ('customer_id', models.CharField(blank=True, max_length=255, verbose_name='Customer ID')),
                ('payment_method_id', models.CharField(blank=True, max_length=255, verbose_name='Payment Method ID')),
                ('card_brand', models.CharField(blank=True, max_length=50, verbose_name='Card Brand')),
                ('card_last4', models.CharField(blank=True, max_length=4, verbose_name='Card Last 4')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_payment', to='payments.transaction')),
            ],
            options={
                'verbose_name': 'پرداخت Stripe',
                'verbose_name_plural': 'پرداخت\u200cهای Stripe',
            },
        ),
        migrations.CreateModel(
            name='CryptoPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cryptocurrency', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'Tether'), ('USDC', 'USD Coin'), ('BNB', 'Binance Coin')], max_length=10, verbose_name='رمزارز')),
                ('network', models.CharField(choices=[('bitcoin', 'Bitcoin Network'), ('ethereum', 'Ethereum Network'), ('bsc', 'Binance Smart Chain'), ('tron', 'Tron Network'), ('polygon', 'Polygon Network')], max_length=20, verbose_name='شبکه')),
                ('wallet_address', models.CharField(max_length=255, verbose_name='آدرس کیف پول مقصد')),
                ('from_address', models.CharField(blank=True, max_length=255, verbose_name='آدرس کیف پول مبدا')),
                ('tx_hash', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Transaction Hash')),
                ('amount_crypto', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='مقدار رمزارز')),
                ('confirmations', models.IntegerField(default=0, verbose_name='تعداد تاییدیه')),
                ('required_confirmations', models.IntegerField(default=3, verbose_name='تاییدیه\u200cهای مورد نیاز')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_payment', to='payments.transaction')),
            ],
            options={
                'verbose_name': 'پرداخت رمزارز',
                'verbose_name_plural': 'پرداخت\u200cهای رمزارز',
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'status'], name='payments_tr_user_id_b99a80_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reference_id'], name='payments_tr_referen_91e1fc_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='payments_tr_created_02ae92_idx'),
        ),
    ]
