# Generated by Django 4.2.7 on 2025-12-29 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='gateway',
            field=models.CharField(choices=[('zarinpal', 'زرین\u200cپال'), ('tejarat_test', 'درگاه تست تجارت'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('crypto', 'Cryptocurrency'), ('bank_transfer', 'انتقال بانکی'), ('credit', 'اعتبار حساب')], max_length=20, verbose_name='درگاه پرداخت'),
        ),
        migrations.CreateModel(
            name='TejaratTestPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='Token')),
                ('card_number', models.CharField(blank=True, max_length=20, verbose_name='شماره کارت')),
                ('tracking_code', models.CharField(blank=True, max_length=100, verbose_name='کد پیگیری')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tejarat_test_payment', to='payments.transaction')),
            ],
            options={
                'verbose_name': 'پرداخت تست تجارت',
                'verbose_name_plural': 'پرداخت\u200cهای تست تجارت',
            },
        ),
    ]
