# Generated by Django 4.2.7 on 2025-12-29 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_transaction_gateway_tejarattestpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlisioPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_id', models.CharField(max_length=255, unique=True, verbose_name='Plisio Transaction ID')),
                ('invoice_url', models.URLField(blank=True, max_length=500, verbose_name='لینک صفحه پرداخت')),
                ('wallet_hash', models.CharField(blank=True, max_length=255, verbose_name='آدرس کیف پول')),
                ('psys_cid', models.CharField(blank=True, max_length=20, verbose_name='ارز دیجیتال (BTC, ETH, USDT, etc.)')),
                ('amount_crypto', models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='مقدار ارز دیجیتال')),
                ('tx_urls', models.JSONField(blank=True, default=list, verbose_name='لینک\u200cهای تراکنش بلاکچین')),
                ('confirmations', models.IntegerField(default=0, verbose_name='تعداد تاییدیه')),
                ('expected_confirmations', models.IntegerField(default=1, verbose_name='تاییدیه\u200cهای مورد نیاز')),
                ('verify_hash', models.CharField(blank=True, max_length=255, verbose_name='Hash تایید')),
            ],
            options={
                'verbose_name': 'پرداخت Plisio',
                'verbose_name_plural': 'پرداخت\u200cهای Plisio',
            },
        ),
        migrations.RemoveField(
            model_name='stripepayment',
            name='transaction',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='gateway',
            field=models.CharField(choices=[('zarinpal', 'زرین\u200cپال'), ('tejarat_test', 'درگاه تست تجارت'), ('plisio', 'پرداخت ارز دیجیتال (Plisio)'), ('credit', 'اعتبار حساب')], max_length=20, verbose_name='درگاه پرداخت'),
        ),
        migrations.DeleteModel(
            name='CryptoPayment',
        ),
        migrations.DeleteModel(
            name='StripePayment',
        ),
        migrations.AddField(
            model_name='plisiopayment',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plisio_payment', to='payments.transaction'),
        ),
    ]
