# Generated by Django 4.2.7 on 2025-12-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_stripe_crypto_add_plisio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='gateway',
            field=models.CharField(choices=[('zarinpal', 'زرین\u200cپال'), ('plisio', 'پرداخت ارز دیجیتال (Plisio)'), ('credit', 'اعتبار حساب')], max_length=20, verbose_name='درگاه پرداخت'),
        ),
        migrations.DeleteModel(
            name='TejaratTestPayment',
        ),
    ]
