# Generated by Django 4.2.7 on 2025-12-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_transaction_gateway_delete_tejarattestpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='شماره فاکتور'),
        ),
    ]
