# Generated by Django 4.2.7 on 2025-12-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_transaction_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=15, verbose_name='نرخ تبدیل'),
        ),
    ]
