# Generated by Django 5.1.3 on 2025-12-20 16:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('icon', models.CharField(default='tag', max_length=50, verbose_name='آیکون')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='رنگ')),
                ('default_priority', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'بالا'), ('urgent', 'فوری')], default='medium', max_length=10, verbose_name='اولویت پیش\u200cفرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='support.ticketcategory', verbose_name='دسته\u200cبندی والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی تیکت',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای تیکت',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TicketDepartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دپارتمان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل دپارتمان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_public', models.BooleanField(default=True, verbose_name='قابل مشاهده برای کاربران')),
                ('auto_assign', models.BooleanField(default=True, verbose_name='تخصیص خودکار')),
                ('priority', models.IntegerField(default=0, verbose_name='اولویت نمایش')),
                ('default_response_time', models.IntegerField(default=24, verbose_name='زمان پاسخ\u200cدهی پیش\u200cفرض (ساعت)')),
                ('default_resolution_time', models.IntegerField(default=72, verbose_name='زمان حل مشکل پیش\u200cفرض (ساعت)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('agents', models.ManyToManyField(blank=True, limit_choices_to={'is_staff': True}, related_name='support_departments', to=settings.AUTH_USER_MODEL, verbose_name='کارشناسان')),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL, verbose_name='مدیر دپارتمان')),
            ],
            options={
                'verbose_name': 'دپارتمان پشتیبانی',
                'verbose_name_plural': 'دپارتمان\u200cهای پشتیبانی',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TicketTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام تگ')),
                ('color', models.CharField(default='#6B7280', max_length=7, verbose_name='رنگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'تگ تیکت',
                'verbose_name_plural': 'تگ\u200cهای تیکت',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ticketcategory',
            name='default_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='support.ticketdepartment', verbose_name='دپارتمان پیش\u200cفرض'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='شماره تیکت')),
                ('subject', models.CharField(max_length=255, verbose_name='موضوع')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('open', 'باز'), ('in_progress', 'در حال بررسی'), ('waiting', 'در انتظار پاسخ کاربر'), ('on_hold', 'معلق'), ('resolved', 'حل شده'), ('closed', 'بسته شده')], default='open', max_length=20, verbose_name='وضعیت')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'بالا'), ('urgent', 'فوری')], default='medium', max_length=10, verbose_name='اولویت')),
                ('source', models.CharField(choices=[('web', 'وب\u200cسایت'), ('email', 'ایمیل'), ('phone', 'تلفن'), ('chat', 'چت'), ('api', 'API')], default='web', max_length=20, verbose_name='منبع')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='تگ\u200cها')),
                ('response_due', models.DateTimeField(blank=True, null=True, verbose_name='مهلت پاسخ\u200cدهی')),
                ('resolution_due', models.DateTimeField(blank=True, null=True, verbose_name='مهلت حل مشکل')),
                ('first_response_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان اولین پاسخ')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان حل مشکل')),
                ('satisfaction_rating', models.IntegerField(blank=True, help_text='از 1 تا 5', null=True, verbose_name='امتیاز رضایت')),
                ('satisfaction_feedback', models.TextField(blank=True, verbose_name='بازخورد رضایت')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='متادیتا')),
                ('user_read', models.BooleanField(default=True, verbose_name='خوانده شده توسط کاربر')),
                ('staff_read', models.BooleanField(default=False, verbose_name='خوانده شده توسط کارشناس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بسته شدن')),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='کارشناس مسئول')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='support.ticketcategory', verbose_name='دسته\u200cبندی')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='support.ticketdepartment', verbose_name='دپارتمان')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='accounts.organization', verbose_name='سازمان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='محتوا')),
                ('message_type', models.CharField(choices=[('reply', 'پاسخ'), ('note', 'یادداشت داخلی'), ('system', 'سیستمی'), ('forward', 'فوروارد')], default='reply', max_length=20, verbose_name='نوع پیام')),
                ('is_staff_reply', models.BooleanField(default=False, verbose_name='پاسخ کارشناس')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='متادیتا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_messages', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.ticket', verbose_name='تیکت')),
            ],
            options={
                'verbose_name': 'پیام تیکت',
                'verbose_name_plural': 'پیام\u200cهای تیکت',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'ایجاد شد'), ('status_changed', 'تغییر وضعیت'), ('priority_changed', 'تغییر اولویت'), ('assigned', 'تخصیص داده شد'), ('forwarded', 'فوروارد شد'), ('department_changed', 'تغییر دپارتمان'), ('category_changed', 'تغییر دسته\u200cبندی'), ('message_added', 'پیام اضافه شد'), ('attachment_added', 'پیوست اضافه شد'), ('merged', 'ادغام شد'), ('split', 'تفکیک شد'), ('reopened', 'بازگشایی شد'), ('closed', 'بسته شد'), ('rated', 'امتیاز داده شد')], max_length=30, verbose_name='عملیات')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='مقدار قبلی')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='مقدار جدید')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='support.ticket', verbose_name='تیکت')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_history_actions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تاریخچه تیکت',
                'verbose_name_plural': 'تاریخچه تیکت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketForward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, verbose_name='دلیل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ فوروارد')),
                ('from_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_tickets', to=settings.AUTH_USER_MODEL, verbose_name='از کارشناس')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwards', to='support.ticket', verbose_name='تیکت')),
                ('to_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_forwards', to=settings.AUTH_USER_MODEL, verbose_name='به کارشناس')),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_forwards', to='support.ticketdepartment', verbose_name='به دپارتمان')),
            ],
            options={
                'verbose_name': 'فوروارد تیکت',
                'verbose_name_plural': 'فوروارد\u200cهای تیکت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='support/attachments/%Y/%m/', verbose_name='فایل')),
                ('file_name', models.CharField(max_length=255, verbose_name='نام فایل')),
                ('file_size', models.IntegerField(verbose_name='حجم فایل')),
                ('mime_type', models.CharField(max_length=100, verbose_name='نوع فایل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support.ticketmessage', verbose_name='پیام')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support.ticket', verbose_name='تیکت')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_attachments', to=settings.AUTH_USER_MODEL, verbose_name='آپلودکننده')),
            ],
            options={
                'verbose_name': 'پیوست تیکت',
                'verbose_name_plural': 'پیوست\u200cهای تیکت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('priority', models.CharField(blank=True, choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'بالا'), ('urgent', 'فوری')], max_length=10, null=True, verbose_name='اولویت')),
                ('response_time', models.IntegerField(verbose_name='زمان پاسخ\u200cدهی (دقیقه)')),
                ('resolution_time', models.IntegerField(verbose_name='زمان حل مشکل (دقیقه)')),
                ('business_hours_only', models.BooleanField(default=True, verbose_name='فقط ساعات کاری')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_policies', to='support.ticketcategory', verbose_name='دسته\u200cبندی')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_policies', to='support.ticketdepartment', verbose_name='دپارتمان')),
            ],
            options={
                'verbose_name': 'سیاست SLA',
                'verbose_name_plural': 'سیاست\u200cهای SLA',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CannedResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('is_public', models.BooleanField(default=True, verbose_name='عمومی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('usage_count', models.IntegerField(default=0, verbose_name='تعداد استفاده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canned_responses', to='support.ticketcategory', verbose_name='دسته\u200cبندی')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canned_responses', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canned_responses', to='support.ticketdepartment', verbose_name='دپارتمان')),
            ],
            options={
                'verbose_name': 'پاسخ آماده',
                'verbose_name_plural': 'پاسخ\u200cهای آماده',
                'ordering': ['-usage_count', 'title'],
            },
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['ticket', 'created_at'], name='support_tic_ticket__0cd9bd_idx'),
        ),
        migrations.AddIndex(
            model_name='tickethistory',
            index=models.Index(fields=['ticket', '-created_at'], name='support_tic_ticket__e3d14e_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['user', '-created_at'], name='support_tic_user_id_b8c0d7_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_to', 'status'], name='support_tic_assigne_6ed26f_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['department', 'status'], name='support_tic_departm_e5ac7d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['ticket_number'], name='support_tic_ticket__d87f40_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', '-priority', '-created_at'], name='support_tic_status_a4df33_idx'),
        ),
    ]
