# Generated by Django manually

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_update_status_and_message_types'),
    ]

    operations = [
        # حذف فیلد business_hours_only
        migrations.RemoveField(
            model_name='slapolicy',
            name='business_hours_only',
        ),
        # حذف فیلد category
        migrations.RemoveField(
            model_name='slapolicy',
            name='category',
        ),
        # تغییر لیبل فیلد name
        migrations.AlterField(
            model_name='slapolicy',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام سیاست'),
        ),
        # تبدیل priority به JSONField برای چندانتخابی
        migrations.AlterField(
            model_name='slapolicy',
            name='priority',
            field=models.JSONField(blank=True, default=list, help_text='می‌توانید چند اولویت انتخاب کنید', verbose_name='اولویت'),
        ),
    ]
