# Generated by Django manually

from django.db import migrations, models
import json


def convert_priority_to_list(apps, schema_editor):
    """تبدیل priority از CharField به JSONField (لیست)"""
    db_alias = schema_editor.connection.alias
    SLAPolicy = apps.get_model('support', 'SLAPolicy')
    
    # استفاده از raw SQL برای تبدیل
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            UPDATE support_slapolicy 
            SET priority_temp = 
                CASE 
                    WHEN priority IS NOT NULL AND priority != '' 
                    THEN json_build_array(priority)::text
                    ELSE '[]'
                END
        """)


def convert_priority_to_string(apps, schema_editor):
    """بازگشت priority از JSONField به CharField"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            UPDATE support_slapolicy 
            SET priority = 
                CASE 
                    WHEN priority_temp::jsonb != '[]'::jsonb 
                    THEN priority_temp::jsonb->>0
                    ELSE NULL
                END
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_update_status_and_message_types'),
    ]

    operations = [
        # حذف فیلد business_hours_only
        migrations.RemoveField(
            model_name='slapolicy',
            name='business_hours_only',
        ),
        # حذف فیلد category
        migrations.RemoveField(
            model_name='slapolicy',
            name='category',
        ),
        # تغییر لیبل فیلد name
        migrations.AlterField(
            model_name='slapolicy',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام سیاست'),
        ),
        # اضافه کردن فیلد موقت برای نگهداری داده‌های JSON
        migrations.AddField(
            model_name='slapolicy',
            name='priority_temp',
            field=models.TextField(null=True, blank=True),
        ),
        # تبدیل داده‌های قدیمی به فرمت JSON
        migrations.RunPython(convert_priority_to_list, convert_priority_to_string),
        # حذف فیلد قدیمی priority
        migrations.RemoveField(
            model_name='slapolicy',
            name='priority',
        ),
        # تغییر نام فیلد موقت به priority
        migrations.RenameField(
            model_name='slapolicy',
            old_name='priority_temp',
            new_name='priority',
        ),
        # تبدیل نوع فیلد به JSONField
        migrations.AlterField(
            model_name='slapolicy',
            name='priority',
            field=models.JSONField(blank=True, default=list, help_text='می‌توانید چند اولویت انتخاب کنید', verbose_name='اولویت'),
        ),
    ]
