# Generated by Django manually

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_update_sla_policy_fields'),
    ]

    operations = [
        # حذف فیلد default_response_time
        migrations.RemoveField(
            model_name='ticketdepartment',
            name='default_response_time',
        ),
        # حذف فیلد default_resolution_time
        migrations.RemoveField(
            model_name='ticketdepartment',
            name='default_resolution_time',
        ),
    ]
