# Generated by Django manually

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_remove_department_sla_fields'),
    ]

    operations = [
        # حذف فیلد parent
        migrations.RemoveField(
            model_name='ticketcategory',
            name='parent',
        ),
    ]
