# Generated by Django manually

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_remove_category_parent'),
    ]

    operations = [
        # حذف فیلد tags از Ticket
        migrations.RemoveField(
            model_name='ticket',
            name='tags',
        ),
        # حذف مدل TicketTag
        migrations.DeleteModel(
            name='TicketTag',
        ),
    ]
