# Generated by Django manually

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_remove_tickettag'),
    ]

    operations = [
        # حذف مدل TicketForward
        migrations.DeleteModel(
            name='TicketForward',
        ),
    ]
