# Generated by Django manually

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_remove_ticketforward'),
    ]

    operations = [
        # حذف مدل TicketAttachment
        migrations.DeleteModel(
            name='TicketAttachment',
        ),
    ]
