# Generated by Django 4.2.7 on 2025-12-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0009_make_category_department_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slapolicy',
            name='department',
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='این سیاست برای کدام دپارتمان\u200cها اعمال شود؟ اگر خالی باشد، برای همه دپارتمان\u200cها اعمال می\u200cشود.', related_name='sla_policies', to='support.ticketdepartment', verbose_name='دپارتمان\u200cها'),
        ),
    ]
