# Generated by Django 4.2.7 on 2025-12-19 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontend_site_name', models.CharField(default='تجارت چت', help_text='نام سایت که در فرانت\u200cاند نمایش داده می\u200cشود', max_length=100, verbose_name='نام سایت کاربران')),
                ('admin_site_name', models.CharField(default='پنل مدیریت تجارت چت', help_text='نام سایت که در پنل مدیریت نمایش داده می\u200cشود', max_length=100, verbose_name='نام پنل مدیریت')),
                ('copyright_text', models.CharField(default='تجارت چت © 2024', help_text='متن کپی\u200cرایت که در پایین پنل مدیریت نمایش داده می\u200cشود', max_length=200, verbose_name='متن کپی\u200cرایت')),
                ('support_email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل پشتیبانی')),
                ('support_phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن پشتیبانی')),
                ('telegram_url', models.URLField(blank=True, verbose_name='آدرس تلگرام')),
                ('instagram_url', models.URLField(blank=True, verbose_name='آدرس اینستاگرام')),
                ('twitter_url', models.URLField(blank=True, verbose_name='آدرس توییتر')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='حالت تعمیر و نگهداری')),
                ('maintenance_message', models.TextField(blank=True, help_text='پیامی که در حالت تعمیر به کاربران نمایش داده می\u200cشود', verbose_name='پیام حالت تعمیر')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_payment_gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_sites', to='finance.paymentgateway', verbose_name='درگاه پرداخت پیش\u200cفرض')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='آخرین ویرایش توسط')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
