# Generated by Django 4.2.7 on 2025-12-08 07:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='کد ارز')),
                ('name', models.CharField(max_length=50, verbose_name='نام ارز')),
                ('symbol', models.CharField(max_length=10, verbose_name='نماد')),
                ('has_decimals', models.BooleanField(default=False, verbose_name='دارای اعشار')),
                ('decimal_places', models.PositiveSmallIntegerField(default=0, help_text='تعداد ارقام اعشار (0 برای تومان/ریال، 2 برای دلار)', verbose_name='تعداد ارقام اعشار')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, help_text='نرخ تبدیل این ارز به واحد پایه سایت (1 = واحد پایه)', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='نرخ تبدیل به واحد پایه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ارز',
                'verbose_name_plural': 'ارزها',
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام درگاه')),
                ('gateway_type', models.CharField(choices=[('zarinpal', 'زرین\u200cپال'), ('idpay', 'آیدی\u200cپی'), ('nextpay', 'نکست\u200cپی'), ('parsian', 'پارسیان'), ('mellat', 'ملت'), ('saman', 'سامان'), ('pasargad', 'پاسارگاد'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], max_length=20, verbose_name='نوع درگاه')),
                ('merchant_id', models.CharField(blank=True, max_length=255, verbose_name='شناسه پذیرنده')),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='کلید API')),
                ('api_secret', models.CharField(blank=True, max_length=255, verbose_name='رمز API')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_sandbox', models.BooleanField(default=False, verbose_name='حالت تست')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='درصد کارمزد')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supported_currencies', models.ManyToManyField(blank=True, related_name='payment_gateways', to='core.currency', verbose_name='ارزهای پشتیبانی شده')),
            ],
            options={
                'verbose_name': 'درگاه پرداخت',
                'verbose_name_plural': 'درگاه\u200cهای پرداخت',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='تجارت چت', max_length=100, verbose_name='نام سایت')),
                ('site_url', models.URLField(default='https://tejarat.chat', verbose_name='آدرس سایت')),
                ('site_description', models.TextField(blank=True, verbose_name='توضیحات سایت')),
                ('support_email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل پشتیبانی')),
                ('support_phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن پشتیبانی')),
                ('telegram_url', models.URLField(blank=True, verbose_name='آدرس تلگرام')),
                ('instagram_url', models.URLField(blank=True, verbose_name='آدرس اینستاگرام')),
                ('twitter_url', models.URLField(blank=True, verbose_name='آدرس توییتر')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='حالت تعمیر و نگهداری')),
                ('maintenance_message', models.TextField(blank=True, help_text='پیامی که در حالت تعمیر به کاربران نمایش داده می\u200cشود', verbose_name='پیام حالت تعمیر')),
                ('allow_registration', models.BooleanField(default=True, verbose_name='امکان ثبت\u200cنام')),
                ('require_email_verification', models.BooleanField(default=True, verbose_name='الزام تأیید ایمیل')),
                ('enable_two_factor', models.BooleanField(default=True, verbose_name='فعال\u200cسازی احراز هویت دو مرحله\u200cای')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_currency', models.ForeignKey(blank=True, help_text='واحد پولی پایه سایت (تومان، ریال، دلار و ...)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='base_for_sites', to='core.currency', verbose_name='واحد پولی پایه')),
                ('default_payment_gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_sites', to='core.paymentgateway', verbose_name='درگاه پرداخت پیش\u200cفرض')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='آخرین ویرایش توسط')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
