# Generated by Django 4.2.7 on 2025-12-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='is_base',
            field=models.BooleanField(default=False, help_text='فقط یک ارز می\u200cتواند ارز پایه باشد. قیمت\u200cها به این ارز ذخیره می\u200cشوند.', verbose_name='ارز پایه'),
        ),
    ]
