# Generated by Django 4.2.7 on 2025-12-21 12:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_move_default_gateway'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='نام زبان')),
                ('code', models.CharField(help_text='مثال: fa, en, ar', max_length=10, unique=True, verbose_name='کد زبان')),
                ('native_name', models.CharField(help_text='مثال: فارسی، English', max_length=100, verbose_name='نام بومی')),
                ('is_rtl', models.BooleanField(default=False, verbose_name='راست به چپ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_default', models.BooleanField(default=False, verbose_name='پیش\u200cفرض')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'زبان',
                'verbose_name_plural': 'زبان\u200cها',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='نام منطقه زمانی')),
                ('code', models.CharField(help_text='مثال: Asia/Tehran', max_length=50, unique=True, verbose_name='کد منطقه')),
                ('utc_offset', models.CharField(help_text='مثال: +03:30, -05:00', max_length=10, verbose_name='اختلاف با UTC')),
                ('display_name', models.CharField(help_text='مثال: تهران (UTC+03:30)', max_length=150, verbose_name='نام نمایشی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_default', models.BooleanField(default=False, verbose_name='پیش\u200cفرض')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'منطقه زمانی',
                'verbose_name_plural': 'مناطق زمانی',
                'ordering': ['order', 'utc_offset'],
            },
        ),
    ]
