# Generated by Django 4.2.7 on 2025-12-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_currency_base_and_plan_simplify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='allow_registration',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='enable_two_factor',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='require_email_verification',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_description',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_name',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_url',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admin_site_name',
            field=models.CharField(default='پنل مدیریت تجارت چت', help_text='نام سایت که در پنل مدیریت نمایش داده می\u200cشود', max_length=100, verbose_name='نام پنل مدیریت'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='frontend_site_name',
            field=models.CharField(default='تجارت چت', help_text='نام سایت که در فرانت\u200cاند نمایش داده می\u200cشود', max_length=100, verbose_name='نام سایت کاربران'),
        ),
    ]
