# Generated by Django 4.2.7 on 2025-12-18 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_update_sitesettings_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='base_currency',
        ),
    ]
