# Generated by Django 4.2.7 on 2025-12-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_language_timezone_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='sms_signature',
            field=models.CharField(blank=True, help_text='این متن به انتهای تمام پیامک\u200cها (به جز OTP) اضافه می\u200cشود', max_length=200, verbose_name='امضای سایت در پیامک'),
        ),
    ]
