# Generated by Django 4.2.7 on 2026-02-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_sms_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='license_1_logo_url',
            field=models.URLField(blank=True, help_text='آدرس لوگو یا بَج مجوز اول', verbose_name='URL لوگو مجوز 1'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='license_1_name',
            field=models.CharField(blank=True, help_text='مثال: نماد اعتماد الکترونیک', max_length=200, verbose_name='نام مجوز 1'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='license_2_logo_url',
            field=models.URLField(blank=True, help_text='آدرس لوگو یا بَج مجوز دوم', verbose_name='URL لوگو مجوز 2'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='license_2_name',
            field=models.CharField(blank=True, help_text='مثال: مجوز وزارت ارتباطات', max_length=200, verbose_name='نام مجوز 2'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='license_3_logo_url',
            field=models.URLField(blank=True, help_text='آدرس لوگو یا بَج مجوز سوم', verbose_name='URL لوگو مجوز 3'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='license_3_name',
            field=models.CharField(blank=True, help_text='مثال: گواهینامه ISO', max_length=200, verbose_name='نام مجوز 3'),
        ),
    ]
