# Generated by Django 4.2.7 on 2025-12-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_base_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgateway',
            name='connected_account',
            field=models.CharField(blank=True, max_length=50, verbose_name='شماره حساب متصل'),
        ),
    ]
