# Generated by Django 4.2.7 on 2025-12-18 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_connected_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentgateway',
            name='gateway_type',
        ),
    ]
