# Generated by Django 4.2.7 on 2025-12-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_gateway_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_text',
            field=models.CharField(default='تجارت چت © 2024', help_text='متن کپی\u200cرایت که در پایین پنل مدیریت نمایش داده می\u200cشود', max_length=200, verbose_name='متن کپی\u200cرایت'),
        ),
    ]
